# Generated by Django 5.2 on 2025-04-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tag',
            field=models.CharField(default='Functional', max_length=50),
        ),
        migrations.AddField(
            model_name='risk',
            name='level',
            field=models.CharField(default='Low', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='mitigation_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
